[package]
name = "smash-arc"
version = "0.1.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2018"

[dependencies]
binrw = { git = "https://github.com/jam1garner/binrw" }
zstd = "0.5.3"
modular-bitfield = "0.9"
thiserror = "1.0.21"
